
package bo.gob.rree.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import bo.gob.rree.ent.ArrayOfEntidadInfo;
import bo.gob.rree.ent.ArrayOfPersonaInfo;
import bo.gob.rree.ent.ObjectFactory;


/**
 * This class was generated by the JAX-WS RI.
 * Oracle JAX-WS 2.1.5
 * Generated source version: 2.1
 * 
 */
@WebService(name = "IPersonas", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IPersonas {


    /**
     * 
     * @param total
     * @param getAcreditadosResult
     * @param inicio
     * @param usuario
     * @param cantidad
     * @param nombreCompleto
     * @param dni
     * @param pass
     */
    @WebMethod(operationName = "GetAcreditados", action = "http://tempuri.org/IPersonas/GetAcreditados")
    @RequestWrapper(localName = "GetAcreditados", targetNamespace = "http://tempuri.org/", className = "bo.gob.rree.ent.GetAcreditados")
    @ResponseWrapper(localName = "GetAcreditadosResponse", targetNamespace = "http://tempuri.org/", className = "bo.gob.rree.ent.GetAcreditadosResponse")
    public void getAcreditados(
        @WebParam(name = "Dni", targetNamespace = "http://tempuri.org/")
        String dni,
        @WebParam(name = "NombreCompleto", targetNamespace = "http://tempuri.org/")
        String nombreCompleto,
        @WebParam(name = "Inicio", targetNamespace = "http://tempuri.org/")
        Integer inicio,
        @WebParam(name = "Cantidad", targetNamespace = "http://tempuri.org/")
        Integer cantidad,
        @WebParam(name = "Total", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.INOUT)
        Holder<Integer> total,
        @WebParam(name = "Usuario", targetNamespace = "http://tempuri.org/")
        String usuario,
        @WebParam(name = "Pass", targetNamespace = "http://tempuri.org/")
        String pass,
        @WebParam(name = "GetAcreditadosResult", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<ArrayOfPersonaInfo> getAcreditadosResult);

    /**
     * 
     * @param total
     * @param codigo
     * @param nombre
     * @param getDirectorioResult
     * @param inicio
     * @param usuario
     * @param cantidad
     * @param pass
     */
    @WebMethod(operationName = "GetDirectorio", action = "http://tempuri.org/IPersonas/GetDirectorio")
    @RequestWrapper(localName = "GetDirectorio", targetNamespace = "http://tempuri.org/", className = "bo.gob.rree.ent.GetDirectorio")
    @ResponseWrapper(localName = "GetDirectorioResponse", targetNamespace = "http://tempuri.org/", className = "bo.gob.rree.ent.GetDirectorioResponse")
    public void getDirectorio(
        @WebParam(name = "Nombre", targetNamespace = "http://tempuri.org/")
        String nombre,
        @WebParam(name = "Codigo", targetNamespace = "http://tempuri.org/")
        Integer codigo,
        @WebParam(name = "Inicio", targetNamespace = "http://tempuri.org/")
        Integer inicio,
        @WebParam(name = "Cantidad", targetNamespace = "http://tempuri.org/")
        Integer cantidad,
        @WebParam(name = "Total", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.INOUT)
        Holder<Integer> total,
        @WebParam(name = "Usuario", targetNamespace = "http://tempuri.org/")
        String usuario,
        @WebParam(name = "Pass", targetNamespace = "http://tempuri.org/")
        String pass,
        @WebParam(name = "GetDirectorioResult", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT)
        Holder<ArrayOfEntidadInfo> getDirectorioResult);

}
