
package bo.gob.rree.ws;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * Oracle JAX-WS 2.1.5
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "Personas", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://www.rree.gob.bo/WsAduana/ConsultaService.svc?wsdl#%7Bhttp%3A%2F%2Ftempuri.org%2F%7DPersonas")
public class Personas
    extends Service
{

    private final static URL PERSONAS_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(bo.gob.rree.ws.Personas.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = bo.gob.rree.ws.Personas.class.getResource(".");
            url = new URL(baseUrl, "http://www.rree.gob.bo/WsAduana/ConsultaService.svc?wsdl#%7Bhttp%3A%2F%2Ftempuri.org%2F%7DPersonas");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://www.rree.gob.bo/WsAduana/ConsultaService.svc?wsdl#%7Bhttp%3A%2F%2Ftempuri.org%2F%7DPersonas', retrying as a local file");
            logger.warning(e.getMessage());
        }
        PERSONAS_WSDL_LOCATION = url;
    }

    public Personas(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Personas() {
        super(PERSONAS_WSDL_LOCATION, new QName("http://tempuri.org/", "Personas"));
    }

    /**
     * 
     * @return
     *     returns IPersonas
     */
    @WebEndpoint(name = "BasicHttpBinding_IPersonas")
    public IPersonas getBasicHttpBindingIPersonas() {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IPersonas"), IPersonas.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IPersonas
     */
    @WebEndpoint(name = "BasicHttpBinding_IPersonas")
    public IPersonas getBasicHttpBindingIPersonas(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IPersonas"), IPersonas.class, features);
    }

}
